// Shared load/persist logic for the routines list — used by both the list
// page and the full-page editor (they mount independently on navigation, so
// there's no cross-route live state to sync; each just loads on mount like
// any other page).
import { useState, useEffect, useRef } from 'react'
import { useAuth } from './auth'
import { getProgramsState, saveProgramsState, deleteProgramById } from './workoutStore'
import { fetchRemoteProgramsState, upsertRemoteProgramsState, deleteRemoteProgramById } from './workoutRemote'
import { emptyProgram, moveInArray, moveItem } from './program'

const EMPTY_STATE = { programs: [], activeId: null }

export function useProgramsState() {
  const { user } = useAuth()
  const [programsState, setProgramsState] = useState(EMPTY_STATE)
  const [loading, setLoading] = useState(true)
  const remoteTimer = useRef(null)

  useEffect(() => {
    let cancelled = false
    async function load() {
      setLoading(true)
      let state
      if (user) {
        try {
          state = await fetchRemoteProgramsState(user.id)
        } catch {
          state = getProgramsState()
        }
      } else {
        state = getProgramsState()
      }
      if (!cancelled) {
        setProgramsState(state)
        setLoading(false)
      }
    }
    load()
    return () => { cancelled = true }
  }, [user])

  // Local persists immediately, always. Remote either debounces (continuous
  // edits like typing) or fires right away (discrete actions like switching,
  // duplicating, deleting — decisive clicks that should feel instant/certain).
  function persistLocal(state) {
    saveProgramsState(state)
  }
  function persistRemoteDebounced(state) {
    if (!user) return
    clearTimeout(remoteTimer.current)
    remoteTimer.current = setTimeout(() => { upsertRemoteProgramsState(user.id, state).catch(() => {}) }, 700)
  }
  function persistRemoteNow(state) {
    if (!user) return
    clearTimeout(remoteTimer.current)
    upsertRemoteProgramsState(user.id, state).catch(() => {})
  }

  // Upsert one routine's edits back into the full list (stable order).
  function saveProgram(nextProgram) {
    setProgramsState((prev) => {
      const idx = prev.programs.findIndex((p) => p.id === nextProgram.id)
      const programs = idx === -1 ? [...prev.programs, nextProgram] : prev.programs.map((p, i) => (i === idx ? nextProgram : p))
      const activeId = prev.activeId || nextProgram.id
      const next = { programs, activeId }
      persistLocal(next)
      persistRemoteDebounced(next)
      return next
    })
  }

  // Add a freshly created routine (its id is already generated by the caller,
  // so it can navigate straight to `/routine/${program.id}` without waiting
  // on this state update).
  function addRoutine(program) {
    setProgramsState((prev) => {
      const next = { programs: [...prev.programs, program], activeId: prev.activeId || program.id }
      persistLocal(next)
      persistRemoteNow(next)
      return next
    })
  }

  function duplicateRoutine(program) {
    const copy = emptyProgram(`${program.name} (copy)`)
    copy.days = JSON.parse(JSON.stringify(program.days))
    // A 7-day rotation must stay a rotation (program.js scheduleMode).
    if (program.schedule) copy.schedule = program.schedule
    addRoutine(copy)
    return copy
  }

  function setActiveRoutine(id) {
    setProgramsState((prev) => {
      const next = { ...prev, activeId: id }
      persistLocal(next)
      persistRemoteNow(next)
      return next
    })
  }

  function moveRoutine(index, delta) {
    setProgramsState((prev) => {
      const next = { ...prev, programs: moveInArray(prev.programs, index, delta) }
      persistLocal(next)
      persistRemoteNow(next)
      return next
    })
  }

  function moveRoutineTo(from, to) {
    setProgramsState((prev) => {
      const next = { ...prev, programs: moveItem(prev.programs, from, to) }
      persistLocal(next)
      persistRemoteNow(next)
      return next
    })
  }

  function deleteRoutine(id) {
    const next = deleteProgramById(id) // local: filters + reassigns active + persists, returns new state
    setProgramsState(next)
    persistRemoteNow(next)
    if (user) deleteRemoteProgramById(user.id, id).catch(() => {})
  }

  return {
    user,
    programsState,
    loading,
    saveProgram,
    addRoutine,
    duplicateRoutine,
    setActiveRoutine,
    moveRoutine,
    moveRoutineTo,
    deleteRoutine,
  }
}
